server:
  port: 8090
spring:
  profiles:
    active: test
  application:
    name: '@artifactId@'
  datasource:
    username: root
    password: ${MYSQL-PWD:root}
    url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

thread-pool:
  thread-name-prefix: default-exe
  core-pool-size: 1
  max-pool-size: 4
  queue-capacity: 10
  keep-alive-seconds: 30
  allow-core-thread-time-out: false
  handler-type: java.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy

